"""empty message

Revision ID: 12e841f6891f
Revises: 8f0535dd21d8
Create Date: 2024-10-05 14:41:24.478519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12e841f6891f'
down_revision = '8f0535dd21d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lotacao', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('arrecadacao', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.drop_column('arrecadacao')
        batch_op.drop_column('lotacao')

    # ### end Alembic commands ###
