"""empty message

Revision ID: 4ceb16fe8bc5
Revises: a6b56717dd0b
Create Date: 2024-10-03 15:27:25.911909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ceb16fe8bc5'
down_revision = 'a6b56717dd0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artistas',
    sa.Column('artista_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('cpf', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefone', sa.String(length=15), nullable=True),
    sa.Column('da_casa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('artista_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefone')
    )
    op.create_table('clientes',
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('cpf', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefone', sa.String(length=15), nullable=True),
    sa.Column('vip', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('cliente_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefone')
    )
    op.create_table('tipos_assentos',
    sa.Column('tipo_assento_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('descricao', sa.String(length=256), nullable=True),
    sa.Column('fator_multi', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('tipo_assento_id')
    )
    op.create_table('tipos_ingressos',
    sa.Column('tipo_assento_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('descricao', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('tipo_assento_id')
    )
    op.drop_table('cliente')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('cliente_id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), nullable=True),
    sa.Column('cpf', sa.VARCHAR(length=100), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('telefone', sa.VARCHAR(length=15), nullable=True),
    sa.Column('vip', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('cliente_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefone')
    )
    op.drop_table('tipos_ingressos')
    op.drop_table('tipos_assentos')
    op.drop_table('clientes')
    op.drop_table('artistas')
    # ### end Alembic commands ###
