"""empty message

Revision ID: a6b56717dd0b
Revises: e9c9b07d1f6e
Create Date: 2024-10-03 15:10:55.235577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6b56717dd0b'
down_revision = 'e9c9b07d1f6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('cpf', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefone', sa.String(length=15), nullable=True),
    sa.Column('vip', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('cliente_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefone')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('usuario_id')

    op.drop_table('cliente')
    # ### end Alembic commands ###
