"""empty message

Revision ID: e9c9b07d1f6e
Revises: 
Create Date: 2024-10-02 20:41:38.216712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9c9b07d1f6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apelido', sa.String(length=80), nullable=True),
    sa.Column('senha', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('telefone', sa.String(length=15), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apelido'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    # ### end Alembic commands ###
